# Generated by Django 3.2.4 on 2021-08-08 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='access_otken',
            new_name='access_token',
        ),
    ]
